### PR TITLE
Fix #254: Resource- and Graph->label claim wrong return type

### LINKED ISSUE #254: EasyRdf_Resource->label claims to return string, but returns EasyRdf_Literal
The documentation (derived from the docstring) for the method EasyRdf_Resource->label claims that it will return a string, but actually it will return an EasyRdf_Literal instance:
http://www.easyrdf.org/docs/api/EasyRdf_Resource.html#method_label

The same applies for EasyRdf_Graph->label:
http://www.easyrdf.org/docs/api/EasyRdf_Graph.html#method_label

I noticed because Scrutinizer complains about code in my project that calls a getValue() on the result, which Scrutinizer thinks is a string but is actually not. See https://scrutinizer-ci.com/g/NatLibFi/Skosmos/issues/master/files/model/VocabularyCategory.php?selectedSeverities%5B0%5D=10&orderField=path&order=asc#inspectioncomment-1482399456

I think the docstring for these two methods should simply be changed to reflect reality.

### PR DESCRIPTION
**Pull request by k00ni**
Fix #254 

Corrects info about return values for `Resource::label` and `Graph::label`.

Thank you @osma for reporting this.

### CODE REVIEW

File: lib/Graph.php [hunk 1]
```diff
@@ -1612,7 +1612,7 @@ public function setType($resource, $type)
      * @param string|null $resource
      * @param string|null $lang
      *
-     * @return string A label for the resource.
+     * @return Literal|null An instance of Literal which contains the label or null.
```
Comment (osma) [inline lib/Graph.php:1615]: Other docstrings seem to use the fully qualified names of classes - should this be `\EasyRdf\Literal` instead of just `Literal`?

File: lib/Resource.php [hunk 2]
```diff
@@ -659,7 +659,7 @@ public function primaryTopic()
      *
      * @param string|null $lang
      *
-     * @return string A label for the resource.
+     * @return Literal|null An instance of Literal which contains the label or null.
```
Comment (osma) [inline lib/Resource.php:662]: Ditto

**Review by osma — COMMENTED** [review]
Not sure if fully qualified class names are required in PHP docstrings

File: lib/Graph.php (hunk 1 above)
Comment (k00ni) [reply lib/Graph.php:1615]: I used the same approach as other function comments, e.g. in `Graph::newAndLoad`.

Comment (k00ni) [reply lib/Graph.php:1615]: But other functions use the full name, so we have an inconsistent naming approach. What is the safe way to do this?

Comment (osma) [reply lib/Graph.php:1615]: You are right. Both ways are used (and seem to work, probably since there is a namespace statement at the top of each file) and there is no apparent consistency. But I think that is a different problem, and should not hold back this PR. So I will approve it.

**Review by osma — APPROVED** [review]
OK after the discussion above

File: lib/Graph.php (hunk 1 above)
Comment (k00ni) [reply lib/Graph.php:1615]: OK

**Comment by zozlak** [comment]
According to the PSR-5 both full and local class names can be used (see [here](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#valid-class-name)) but:
* PSR-5 is only a draft
* At the end of the day the question is if your documentation generator and/or IDE supports it (phpDocumentator and Netbeans do but I can't tell about others)

**Comment by k00ni** [comment]
@williamdes: you contributed Doctum for PHPDoc. Can you tell us if it supports both short and fully qualified class names?

**Comment by osma** [comment]
It seems to me that the EasyRdf API documentation generation works in some cases, but not in others.

e.g. https://www.easyrdf.org/docs/api/EasyRdf/Resource.html#method_getResource - the return type Resource is a link to the Resource class 

but https://www.easyrdf.org/docs/api/EasyRdf/Resource.html#method_typeAsResource - the return type Resource is just text with no link

I suspect this is unrelated to the use of namespaces though, since both are specified with the short name `Resource` at least on the current master branch.

**Comment by williamdes** [comment]
> @williamdes: you contributed Doctum for PHPDoc generation (#355). Can you tell us if it supports both short and fully qualified class names?

It supports both from what I could see, be sure to have the right `use` in the file if it is not in the same namespace.

**Comment by k00ni** [comment]
What do you think here @njh?

**Comment by k00ni** [comment]
Please review @njh

**Comment by njh** [comment]
I just tested documentation generation using doctum and `Literal` was a plain string and not a hyperlink to the class.
(I tested this by running `make clean apidocs`)

Changing it to `\EasyRdf\Literal` fixed the problem.
Given that `\EasyRdf\Resource` is used elsewhere in the Docblocks, I think it is probably best to use the full namespace for now.

**Comment by njh** [comment]
I just tried testing this but the API docs build failed, I think due to this:
https://github.com/code-lts/doctum/issues/16

**Comment by williamdes** [comment]
> I just tried testing this but the API docs build failed, I think due to this:
> [code-lts/doctum#16](https://github.com/code-lts/doctum/issues/16)

I just released [5.2.1](https://github.com/code-lts/doctum/releases/tag/v5.2.1) for that ;)
Let me know if something else pops out

**Review by njh — APPROVED** [review]
Successfully built API docs and looks good 👍

**Comment by njh** [comment]
This was released as 1.1.1, which has now been published to the website:
https://www.easyrdf.org/docs/api/EasyRdf/Graph.html
